import { IconChrome, IconCommand, IconPattern, IconSchedule } from "../icons";
import { CTAButton, Eyebrow, PageHeader, Reveal } from "../ui";

const team = [
  { name: "Varun Bhadurgatte Nagaraj", role: "Founder · Lead developer", initials: "VN", body: "Started HallHop after noticing how much hallway movement depended on paper, memory, and guesswork. Leads the product and technical direction." },
  { name: "Rithul Bhat", role: "Co-founder · Developer", initials: "RB", body: "Helped shape the teacher-side experience, with an emphasis on reliable pass decisions and practical classroom workflows." },
  { name: "Maanya Shekar", role: "Co-founder · Outreach", initials: "MS", body: "Contributed to the project’s early structure, documentation, and outreach to the school community." },
];

export function AboutPage() {
  return <main id="main">
    <PageHeader eyebrow="Our story" title="Built inside the problem." accent="Not around it."><p>HallHop started with students looking at a normal school day and asking a useful question: why does movement between classrooms still depend on paper and guesswork?</p></PageHeader>

    <section className="ink-section"><div className="shell grid gap-16 py-[clamp(5rem,10vw,10rem)] lg:grid-cols-[0.65fr_1.35fr]"><Reveal><Eyebrow className="text-chalk">The beginning</Eyebrow><p className="mt-6 font-mono text-xs uppercase tracking-wider text-paper/45">Texas · 2025</p></Reveal><Reveal delay={0.05}><p className="display max-w-[14ch] text-[clamp(3.4rem,7vw,7rem)]">A few lines of code became a different way to see the school day.</p><div className="mt-10 grid gap-8 text-lg leading-relaxed text-paper/65 sm:grid-cols-2"><p>The first HallHop work focused on a Chrome extension that could understand a student’s schedule and make checking out and returning straightforward.</p><p>That led to a larger idea: connect the student moment, the teacher decision, and the school-wide view without turning movement into surveillance.</p></div></Reveal></div></section>

    <section className="fresh-section"><div className="shell py-[clamp(5rem,9vw,9rem)]"><Reveal><Eyebrow>What has stayed true</Eyebrow><h2 className="display mt-8 max-w-5xl text-[clamp(3.5rem,7vw,7rem)]">Technology should make a school feel more understandable—not more watched.</h2></Reveal><div className="mt-16 grid border-y border-ink lg:grid-cols-3">{[["01", "Student perspective", "Build with the reality of the people moving through the system."], ["02", "Teacher attention", "Measure success partly by how little the workflow interrupts instruction."], ["03", "Responsible context", "Give authorized people useful information with clear boundaries around it."]].map(([n, title, body], i) => <Reveal key={n} delay={i * 0.04} className={`p-8 ${i ? "border-t border-ink lg:border-l lg:border-t-0" : ""}`}><span className="font-mono text-xs text-accent">{n}</span><h3 className="display mt-16 text-4xl">{title}</h3><p className="mt-5 leading-relaxed text-ink-2">{body}</p></Reveal>)}</div></div></section>

    <section className="signal-section border-y border-ink"><div className="shell py-[clamp(5rem,8vw,8rem)]"><Reveal><Eyebrow>The founding team</Eyebrow><h2 className="display mt-8 text-[clamp(3.5rem,7vw,6.8rem)]">Students building for schools.</h2></Reveal><div className="mt-14 grid border-t border-ink lg:grid-cols-3">{team.map((member, i) => <Reveal key={member.name} delay={i * 0.04} className={`border-b border-ink p-7 sm:p-9 ${i ? "lg:border-l" : ""}`}><span className="display grid h-16 w-16 place-items-center border border-ink bg-paper text-2xl">{member.initials}</span><p className="mt-10 font-mono text-[10px] uppercase tracking-wider">{member.role}</p><h3 className="display mt-4 text-3xl">{member.name}</h3><p className="mt-5 leading-relaxed">{member.body}</p></Reveal>)}</div></div></section>

    <section className="section"><div className="shell grid gap-14 lg:grid-cols-[0.75fr_1.25fr]"><Reveal><Eyebrow>Still building</Eyebrow><h2 className="display mt-8 text-5xl sm:text-6xl">The work now.</h2></Reveal><Reveal delay={0.05}><div className="border-t border-ink">{[[IconCommand, "Teacher command", "Refining the fastest daily decisions"], [IconPattern, "Pattern review", "Keeping signals explainable and human-reviewed"], [IconSchedule, "Schedule intelligence", "Strengthening Home Access Center context"], [IconChrome, "Browser experience", "Making the student flow feel nearly invisible"]].map(([I, title, body]) => { const Icon = I as typeof IconCommand; return <div key={title as string} className="grid min-h-24 grid-cols-[48px_1fr] items-center gap-5 border-b border-ink py-5"><Icon className="h-7 w-7 text-accent" /><div><h3 className="font-semibold">{title as string}</h3><p className="mt-1 text-sm text-ink-2">{body as string}</p></div></div>; })}</div></Reveal></div></section>

    <section className="chalk-section border-y border-ink"><div className="shell flex flex-col items-start justify-between gap-8 py-16 lg:flex-row lg:items-center"><div><p className="display text-5xl sm:text-6xl">Start a conversation.</p><p className="mt-3 text-lg">Tell us what movement looks like at your campus.</p></div><CTAButton href="/contact" secondary>Contact sales</CTAButton></div></section>
  </main>;
}
