import Link from "next/link";
import { IconArrow, IconPaper, IconShield } from "../icons";
import { Eyebrow, PageHeader, Reveal } from "../ui";

const resources = [
  { type: "Field note · 6 min", title: "What to map before replacing paper passes", body: "A practical inventory of roles, destinations, schedules, exceptions, and the small classroom moments a rollout must respect.", href: "#pilot" },
  { type: "Trust brief · 5 min", title: "Visibility is not the same as surveillance", body: "A framework for drawing boundaries around access, pattern review, transparency, and school-owned decisions.", href: "#trust" },
  { type: "Technical note · 4 min", title: "Why schedule context changes the pass", body: "A/B days, split lunches, rooms, and period changes are operational data—not setup trivia.", href: "#schedule" },
];

export function ResourcesPage() {
  return <main id="main">
    <PageHeader eyebrow="Resources" title="Useful thinking." accent="No gated PDF."><p>Short notes for school teams evaluating digital movement systems, written from the product decisions HallHop has had to make.</p></PageHeader>
    <section className="fresh-section"><div className="shell py-[clamp(5rem,9vw,9rem)]"><div className="grid border-t border-ink lg:grid-cols-3">{resources.map((item, i) => <Reveal key={item.title} delay={i * 0.04} className={`min-h-[390px] border-b border-ink p-8 ${i ? "lg:border-l" : ""}`}><IconPaper className="h-8 w-8 text-accent" /><p className="mt-10 font-mono text-[10px] uppercase tracking-wider text-faint">{item.type}</p><h2 className="display mt-5 text-4xl">{item.title}</h2><p className="mt-5 leading-relaxed text-ink-2">{item.body}</p><Link href={item.href} prefetch={false} className="link-arrow mt-7">Read below <IconArrow className="h-5 w-5" /></Link></Reveal>)}</div></div></section>
    <article id="pilot" className="ink-section scroll-mt-24"><div className="shell grid gap-12 py-[clamp(5rem,8vw,8rem)] lg:grid-cols-[0.7fr_1.3fr]"><Reveal><Eyebrow className="text-chalk">Field note 01</Eyebrow><h2 className="display mt-8 text-5xl">Map the exceptions first.</h2></Reveal><Reveal delay={0.05} className="space-y-6 text-lg leading-relaxed text-paper/70"><p>A pass workflow looks simple until the bell schedule changes, the nurse needs a longer default, a student returns during a transition, or the front office creates a pass on someone’s behalf.</p><p>Before choosing software, map who can request, who can approve, which destinations behave differently, and what should happen when the normal flow breaks. The exception list is often a better product test than the feature list.</p></Reveal></div></article>
    <article id="trust" className="signal-section scroll-mt-24"><div className="shell grid gap-12 py-[clamp(5rem,8vw,8rem)] lg:grid-cols-[0.7fr_1.3fr]"><Reveal><IconShield className="h-10 w-10" /><Eyebrow className="mt-8">Trust brief 02</Eyebrow><h2 className="display mt-8 text-5xl">Ask who can see what.</h2></Reveal><Reveal delay={0.05} className="space-y-6 text-lg leading-relaxed"><p>“Real time” is not a complete access policy. A trustworthy system defines the view for each role, explains why each field is present, and makes it possible to review sensitive actions.</p><p>Pattern detection deserves the same clarity. A signal should be explainable, reviewable, and incapable of becoming an automatic punishment.</p></Reveal></div></article>
    <article id="schedule" className="chalk-section scroll-mt-24"><div className="shell grid gap-12 py-[clamp(5rem,8vw,8rem)] lg:grid-cols-[0.7fr_1.3fr]"><Reveal><Eyebrow>Technical note 03</Eyebrow><h2 className="display mt-8 text-5xl">Time only makes sense in context.</h2></Reveal><Reveal delay={0.05} className="space-y-6 text-lg leading-relaxed"><p>Seven minutes means something different during a standard period, a passing window, and a split lunch. Room distance, destination, and day type matter too.</p><p>That is why HallHop treats schedule intelligence as part of the pass itself. Better context produces calmer alerts and fairer conversations.</p></Reveal></div></article>
  </main>;
}
